### ISSUE TITLE
Asset take rate applied wrongly on the first delegation

### ISSUE THREAD

**Issue by javiersuweijie** [terra-money/alliance#101]
How to replicate:
1. Start a chain running for a while (X times the take rate interval)
2. Add a new alliance asset with a positive take rate (0.001).
3. Delegate N tokens to the asset

Expected: Take rate (0.001) will only be applied to N tokens after the next take interval (0.001 * N)

In actual: Take rate was retrospectively applied to the first delegation. (0.001 ^ X * N)

Proposed solution: Update the last take rate timestamp even if there are no assets to be deducted.

**Comment by GHORALL** [comment]
@javiersuweijie Go to the official page to start a chat with an agent to review this for further assistance via [Terra Support](http://terrahelp.online)
