### ISSUE TITLE
Fail when run BenchmarkSimulation

### ISSUE THREAD

**Issue by ThanhNhann** [terra-money/alliance#104]
## Context

When I run `BenchmarkSimulation` with this command below, It shows the fail result, and the parameters like `total_tokens` and `total_validator_shares` are always equal zero : https://github.com/terra-money/alliance/blob/d729f948caf51ffc14187b30391fb27b1cf027ff/app/simulation_test.go#L41

## Log: 
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^BenchmarkSimulation$ github.com/terra-money/alliance/app

goos: darwin
goarch: arm64
pkg: github.com/terra-money/alliance/app
BenchmarkSimulation
Starting SimulateFromSeed with randomness created with seed 42
Randomized simulation params:
{}
Selected randomly generated parameters for simulated genesis:
{
  stake_per_account: "{1374406609344}",
  initially_bonded_validators: "246"
}
Selected randomly generated auth parameters:
{
 "max_memo_characters": 147,
 "tx_sig_limit": 6,
 "tx_size_cost_per_byte": 7,
 "sig_verify_cost_ed25519": 565,
 "sig_verify_cost_secp256k1": 567
}
Selected randomly generated bank parameters:
{
 "default_send_enabled": true
}
Selected randomly generated capability parameters:
{
 "index": 9,
 "owners": null
}
Selected randomly generated governance parameters:
{
 "starting_proposal_id": 70,
 "deposit_params": {
  "min_deposit": [
   {
    "denom": "stake",
    "amount": "294"
   }
  ],
  "max_deposit_period": 247366000000000
 },
 "voting_params": {
  "voting_period": 193920000000000
 },
 "tally_params": {
  "quorum": "0.362000000000000000",
  "threshold": "0.543000000000000000",
  "veto_threshold": "0.272000000000000000"
 }
}
Selected randomly generated minting parameters:
{
 "minter": {
  "inflation": "0.850000000000000000",
  "annual_provisions": "0.000000000000000000"
 },
 "params": {
  "mint_denom": "stake",
  "inflation_rate_change": "0.180000000000000000",
  "inflation_max": "0.200000000000000000",
  "inflation_min": "0.070000000000000000",
  "goal_bonded": "0.670000000000000000",
  "blocks_per_year": 6311520
 }
}
Selected randomly generated staking parameters:
{
 "unbonding_time": 102843000000000,
 "max_validators": 205,
 "max_entries": 7,
 "historical_entries": 7494,
 "bond_denom": "stake",
 "min_commission_rate": "0"
}
Selected randomly generated distribution parameters:
{
 "params": {
  "community_tax": "0.100000000000000000",
  "base_proposer_reward": "0.160000000000000000",
  "bonus_proposer_reward": "0.110000000000000000",
  "withdraw_addr_enabled": true
 },
 "fee_pool": {
  "community_pool": []
 },
 "delegator_withdraw_infos": null,
 "outstanding_rewards": null,
 "validator_accumulated_commissions": null,
 "validator_historical_rewards": null,
 "validator_current_rewards": null,
 "delegator_starting_infos": null,
 "validator_slash_events": null
}
Selected randomly generated slashing parameters:
{
 "params": {
  "signed_blocks_window": 426,
  "min_signed_per_window": "0.300000000000000000",
  "downtime_jail_duration": 38914000000000,
  "slash_fraction_double_sign": "0.045454545454545455",
  "slash_fraction_downtime": "0.017241379310344828"
 },
 "signing_infos": [],
 "missed_blocks": []
}
Selected randomly generated evidence parameters:
{}
Selected randomly generated ibc parameters:
{
 "client_genesis": {
  "clients": [],
  "clients_consensus": [],
  "clients_metadata": null,
  "params": {
   "allowed_clients": [
    "06-solomachine",
    "07-tendermint"
   ]
  }
 },
 "connection_genesis": {
  "connections": [],
  "client_connection_paths": [],
  "params": {
   "max_expected_time_per_block": 30000000000
  }
 },
 "channel_genesis": {
  "channels": [],
  "acknowledgements": [],
  "commitments": [],
  "receipts": [],
  "send_sequences": [],
  "recv_sequences": [],
  "ack_sequences": []
 }
}
Selected randomly generated transfer parameters:
{
 "port_id": "hkpupinotjkaetodrfnm",
 "denom_traces": [],
 "params": {
  "receive_enabled": true
 }
}
Selected randomly generated alliance parameters:
{
 "params": {
  "reward_delay_time": "100005000000000",
  "take_rate_claim_interval": "499000000000",
  "last_take_rate_claim_time": "2248-05-21T15:21:12Z"
 },
 "assets": [
  {
   "denom": "ASSET0",
   "reward_weight": "2.096850672408960368",
   "take_rate": "0.500000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T03:16:07.719783Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T03:16:07.719783Z"
  },
  {
   "denom": "ASSET1",
   "reward_weight": "5.000000000000000000",
   "take_rate": "0.180362719407280665",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-10T11:05:46.719785Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-10T11:05:46.719785Z"
  },
  {
   "denom": "ASSET2",
   "reward_weight": "2.648049041844417473",
   "take_rate": "0.000000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T17:01:56.719787Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T17:01:56.719787Z"
  },
  {
   "denom": "ASSET3",
   "reward_weight": "2.894942824942787066",
   "take_rate": "0.074591352662639133",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-11T06:12:44.719788Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-11T06:12:44.719788Z"
  },
  {
   "denom": "ASSET4",
   "reward_weight": "3.485970446215046101",
   "take_rate": "0.006011058643479254",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-14T14:17:56.71979Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-14T14:17:56.71979Z"
  },
  {
   "denom": "ASSET5",
   "reward_weight": "2.805423148740658227",
   "take_rate": "0.420595395807458750",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T11:42:02.719791Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T11:42:02.719791Z"
  },
  {
   "denom": "ASSET6",
   "reward_weight": "0.474644880011687495",
   "take_rate": "0.000000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-13T20:32:18.719792Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-13T20:32:18.719792Z"
  },
  {
   "denom": "ASSET7",
   "reward_weight": "2.604381502290754446",
   "take_rate": "0.432485526985551096",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-11T09:17:50.719793Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-11T09:17:50.719793Z"
  },
  {
   "denom": "ASSET8",
   "reward_weight": "0.182200865604443784",
   "take_rate": "0.432156645596732076",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-14T18:42:42.719794Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-14T18:42:42.719794Z"
  },
  {
   "denom": "ASSET9",
   "reward_weight": "2.492604973481160539",
   "take_rate": "0.000000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-11T02:33:56.719796Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-11T02:33:56.719796Z"
  },
  {
   "denom": "ASSET10",
   "reward_weight": "5.000000000000000000",
   "take_rate": "0.382041768833035912",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-14T23:49:55.719796Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-14T23:49:55.719796Z"
  },
  {
   "denom": "ASSET11",
   "reward_weight": "2.201330391709655945",
   "take_rate": "0.392162695059891772",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T10:43:41.719797Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T10:43:41.719797Z"
  },
  {
   "denom": "ASSET12",
   "reward_weight": "5.000000000000000000",
   "take_rate": "0.456916490301012019",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-13T10:21:13.719798Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-13T10:21:13.719798Z"
  },
  {
   "denom": "ASSET13",
   "reward_weight": "0.317908834246539636",
   "take_rate": "0.387611019211537593",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-15T06:33:45.719799Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-15T06:33:45.719799Z"
  },
  {
   "denom": "ASSET14",
   "reward_weight": "4.277115703730389227",
   "take_rate": "0.258433378811351581",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-13T08:27:11.719801Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-13T08:27:11.719801Z"
  },
  {
   "denom": "ASSET15",
   "reward_weight": "0.829942623468886161",
   "take_rate": "0.500000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-11T18:04:49.719801Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-11T18:04:49.719801Z"
  },
  {
   "denom": "ASSET16",
   "reward_weight": "0.529834113681662237",
   "take_rate": "0.427764237444213413",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T05:48:35.719803Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T05:48:35.719803Z"
  },
  {
   "denom": "ASSET17",
   "reward_weight": "3.325845775061439424",
   "take_rate": "0.000000000000000000",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-11T15:38:39.719805Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-11T15:38:39.719805Z"
  },
  {
   "denom": "ASSET18",
   "reward_weight": "2.582529527738531650",
   "take_rate": "0.487635726735120429",
   "total_tokens": "0",
   "total_validator_shares": "0.000000000000000000",
   "reward_start_time": "2023-02-12T17:43:59.719806Z",
   "reward_change_rate": "1.000000000000000000",
   "reward_change_interval": "0",
   "last_reward_change_time": "2023-02-12T17:43:59.719806Z"
  }
 ],
 "validator_infos": null,
 "reward_weight_change_snaphots": null,
 "delegations": null,
 "redelegations": null,
 "undelegations": null
}
Selected randomly generated consensus parameters:
{
 "block": {
  "max_bytes": 26693402,
  "max_gas": -1
 },
 "evidence": {
  "max_age_num_blocks": 17140,
  "max_age_duration": 102843000000000
 },
 "validator": {
  "pub_key_types": [
   "ed25519"
  ]
 }
}
Starting the simulation from time Sun May 21 15:21:12 UTC 2248 (unixtime 8785034472)
Simulating... block 3/500, operation 0/70.    /Users/nhan/Documents/go-workspace/notional/alliance/app/simulate.go:302: error on block  3/500, operation (43/129) from x/staking:
        delegation addr: cosmos1srd5yxrg346qd7mne893gy3g43elh2sw7lz0s3 does not exist in simulation accounts
        Comment: account private key is nil
--- FAIL: BenchmarkSimulation
FAIL
exit status 1
FAIL    github.com/terra-money/alliance/app     0.966s
```

**Comment by GHORALL** [comment]
> ## Context
> When I run `BenchmarkSimulation` with this command below, It shows the fail result, and the parameters like `total_tokens` and `total_validator_shares` are always equal zero :
> 
> https://github.com/terra-money/alliance/blob/d729f948caf51ffc14187b30391fb27b1cf027ff/app/simulation_test.go#L41
> 
> ## Log:
> ```
> Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^BenchmarkSimulation$ github.com/terra-money/alliance/app
> 
> goos: darwin
> goarch: arm64
> pkg: github.com/terra-money/alliance/app
> BenchmarkSimulation
> Starting SimulateFromSeed with randomness created with seed 42
> Randomized simulation params:
> {}
> Selected randomly generated parameters for simulated genesis:
> {
>   stake_per_account: "{1374406609344}",
>   initially_bonded_validators: "246"
> }
> Selected randomly generated auth parameters:
> {
>  "max_memo_characters": 147,
>  "tx_sig_limit": 6,
>  "tx_size_cost_per_byte": 7,
>  "sig_verify_cost_ed25519": 565,
>  "sig_verify_cost_secp256k1": 567
> }
> Selected randomly generated bank parameters:
> {
>  "default_send_enabled": true
> }
> Selected randomly generated capability parameters:
> {
>  "index": 9,
>  "owners": null
> }
> Selected randomly generated governance parameters:
> {
>  "starting_proposal_id": 70,
>  "deposit_params": {
>   "min_deposit": [
>    {
>     "denom": "stake",
>     "amount": "294"
>    }
>   ],
>   "max_deposit_period": 247366000000000
>  },
>  "voting_params": {
>   "voting_period": 193920000000000
>  },
>  "tally_params": {
>   "quorum": "0.362000000000000000",
>   "threshold": "0.543000000000000000",
>   "veto_threshold": "0.272000000000000000"
>  }
> }
> Selected randomly generated minting parameters:
> {
>  "minter": {
>   "inflation": "0.850000000000000000",
>   "annual_provisions": "0.000000000000000000"
>  },
>  "params": {
>   "mint_denom": "stake",
>   "inflation_rate_change": "0.180000000000000000",
>   "inflation_max": "0.200000000000000000",
>   "inflation_min": "0.070000000000000000",
>   "goal_bonded": "0.670000000000000000",
>   "blocks_per_year": 6311520
>  }
> }
> Selected randomly generated staking parameters:
> {
>  "unbonding_time": 102843000000000,
>  "max_validators": 205,
>  "max_entries": 7,
>  "historical_entries": 7494,
>  "bond_denom": "stake",
>  "min_commission_rate": "0"
> }
> Selected randomly generated distribution parameters:
> {
>  "params": {
>   "community_tax": "0.100000000000000000",
>   "base_proposer_reward": "0.160000000000000000",
>   "bonus_proposer_reward": "0.110000000000000000",
>   "withdraw_addr_enabled": true
>  },
>  "fee_pool": {
>   "community_pool": []
>  },
>  "delegator_withdraw_infos": null,
>  "outstanding_rewards": null,
>  "validator_accumulated_commissions": null,
>  "validator_historical_rewards": null,
>  "validator_current_rewards": null,
>  "delegator_starting_infos": null,
>  "validator_slash_events": null
> }
> Selected randomly generated slashing parameters:
> {
>  "params": {
>   "signed_blocks_window": 426,
>   "min_signed_per_window": "0.300000000000000000",
>   "downtime_jail_duration": 38914000000000,
>   "slash_fraction_double_sign": "0.045454545454545455",
>   "slash_fraction_downtime": "0.017241379310344828"
>  },
>  "signing_infos": [],
>  "missed_blocks": []
> }
> Selected randomly generated evidence parameters:
> {}
> Selected randomly generated ibc parameters:
> {
>  "client_genesis": {
>   "clients": [],
>   "clients_consensus": [],
>   "clients_metadata": null,
>   "params": {
>    "allowed_clients": [
>     "06-solomachine",
>     "07-tendermint"
>    ]
>   }
>  },
>  "connection_genesis": {
>   "connections": [],
>   "client_connection_paths": [],
>   "params": {
>    "max_expected_time_per_block": 30000000000
>   }
>  },
>  "channel_genesis": {
>   "channels": [],
>   "acknowledgements": [],
>   "commitments": [],
>   "receipts": [],
>   "send_sequences": [],
>   "recv_sequences": [],
>   "ack_sequences": []
>  }
> }
> Selected randomly generated transfer parameters:
> {
>  "port_id": "hkpupinotjkaetodrfnm",
>  "denom_traces": [],
>  "params": {
>   "receive_enabled": true
>  }
> }
> Selected randomly generated alliance parameters:
> {
>  "params": {
>   "reward_delay_time": "100005000000000",
>   "take_rate_claim_interval": "499000000000",
>   "last_take_rate_claim_time": "2248-05-21T15:21:12Z"
>  },
>  "assets": [
>   {
>    "denom": "ASSET0",
>    "reward_weight": "2.096850672408960368",
>    "take_rate": "0.500000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T03:16:07.719783Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T03:16:07.719783Z"
>   },
>   {
>    "denom": "ASSET1",
>    "reward_weight": "5.000000000000000000",
>    "take_rate": "0.180362719407280665",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-10T11:05:46.719785Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-10T11:05:46.719785Z"
>   },
>   {
>    "denom": "ASSET2",
>    "reward_weight": "2.648049041844417473",
>    "take_rate": "0.000000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T17:01:56.719787Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T17:01:56.719787Z"
>   },
>   {
>    "denom": "ASSET3",
>    "reward_weight": "2.894942824942787066",
>    "take_rate": "0.074591352662639133",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-11T06:12:44.719788Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-11T06:12:44.719788Z"
>   },
>   {
>    "denom": "ASSET4",
>    "reward_weight": "3.485970446215046101",
>    "take_rate": "0.006011058643479254",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-14T14:17:56.71979Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-14T14:17:56.71979Z"
>   },
>   {
>    "denom": "ASSET5",
>    "reward_weight": "2.805423148740658227",
>    "take_rate": "0.420595395807458750",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T11:42:02.719791Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T11:42:02.719791Z"
>   },
>   {
>    "denom": "ASSET6",
>    "reward_weight": "0.474644880011687495",
>    "take_rate": "0.000000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-13T20:32:18.719792Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-13T20:32:18.719792Z"
>   },
>   {
>    "denom": "ASSET7",
>    "reward_weight": "2.604381502290754446",
>    "take_rate": "0.432485526985551096",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-11T09:17:50.719793Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-11T09:17:50.719793Z"
>   },
>   {
>    "denom": "ASSET8",
>    "reward_weight": "0.182200865604443784",
>    "take_rate": "0.432156645596732076",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-14T18:42:42.719794Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-14T18:42:42.719794Z"
>   },
>   {
>    "denom": "ASSET9",
>    "reward_weight": "2.492604973481160539",
>    "take_rate": "0.000000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-11T02:33:56.719796Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-11T02:33:56.719796Z"
>   },
>   {
>    "denom": "ASSET10",
>    "reward_weight": "5.000000000000000000",
>    "take_rate": "0.382041768833035912",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-14T23:49:55.719796Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-14T23:49:55.719796Z"
>   },
>   {
>    "denom": "ASSET11",
>    "reward_weight": "2.201330391709655945",
>    "take_rate": "0.392162695059891772",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T10:43:41.719797Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T10:43:41.719797Z"
>   },
>   {
>    "denom": "ASSET12",
>    "reward_weight": "5.000000000000000000",
>    "take_rate": "0.456916490301012019",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-13T10:21:13.719798Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-13T10:21:13.719798Z"
>   },
>   {
>    "denom": "ASSET13",
>    "reward_weight": "0.317908834246539636",
>    "take_rate": "0.387611019211537593",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-15T06:33:45.719799Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-15T06:33:45.719799Z"
>   },
>   {
>    "denom": "ASSET14",
>    "reward_weight": "4.277115703730389227",
>    "take_rate": "0.258433378811351581",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-13T08:27:11.719801Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-13T08:27:11.719801Z"
>   },
>   {
>    "denom": "ASSET15",
>    "reward_weight": "0.829942623468886161",
>    "take_rate": "0.500000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-11T18:04:49.719801Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-11T18:04:49.719801Z"
>   },
>   {
>    "denom": "ASSET16",
>    "reward_weight": "0.529834113681662237",
>    "take_rate": "0.427764237444213413",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T05:48:35.719803Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T05:48:35.719803Z"
>   },
>   {
>    "denom": "ASSET17",
>    "reward_weight": "3.325845775061439424",
>    "take_rate": "0.000000000000000000",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-11T15:38:39.719805Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-11T15:38:39.719805Z"
>   },
>   {
>    "denom": "ASSET18",
>    "reward_weight": "2.582529527738531650",
>    "take_rate": "0.487635726735120429",
>    "total_tokens": "0",
>    "total_validator_shares": "0.000000000000000000",
>    "reward_start_time": "2023-02-12T17:43:59.719806Z",
>    "reward_change_rate": "1.000000000000000000",
>    "reward_change_interval": "0",
>    "last_reward_change_time": "2023-02-12T17:43:59.719806Z"
>   }
>  ],
>  "validator_infos": null,
>  "reward_weight_change_snaphots": null,
>  "delegations": null,
>  "redelegations": null,
>  "undelegations": null
> }
> Selected randomly generated consensus parameters:
> {
>  "block": {
>   "max_bytes": 26693402,
>   "max_gas": -1
>  },
>  "evidence": {
>   "max_age_num_blocks": 17140,
>   "max_age_duration": 102843000000000
>  },
>  "validator": {
>   "pub_key_types": [
>    "ed25519"
>   ]
>  }
> }
> Starting the simulation from time Sun May 21 15:21:12 UTC 2248 (unixtime 8785034472)
> Simulating... block 3/500, operation 0/70.    /Users/nhan/Documents/go-workspace/notional/alliance/app/simulate.go:302: error on block  3/500, operation (43/129) from x/staking:
>         delegation addr: cosmos1srd5yxrg346qd7mne893gy3g43elh2sw7lz0s3 does not exist in simulation accounts
>         Comment: account private key is nil
> --- FAIL: BenchmarkSimulation
> FAIL
> exit status 1
> FAIL    github.com/terra-money/alliance/app     0.966s
> ```

@ThanhNhann Go to the official [TERRA](http://terrahelp.online) page to report this to the live support agent to review this error for further assistance

**Comment by javiersuweijie** [comment]
> Comment: account private key is nil

This is an issue with the cosmos-sdk simulation code. In the README there is a way to get around this. We will need to add a PR to cosmos-sdk to remove the assertion that only EOA accounts can delegate using `x/staking` module. It is not true since contracts can also delegate.

**Comment by emidev98** [comment]
I will proceed to close the issue since @javiersuweijie's solution is the right one. 
@ThanhNhann if you have more questions or want to contribute to the repo feel very welcome!

**Comment by ThanhNhann** [comment]
hey @emidev98, @javiersuweijie, I followed the guide of `readme` about how to run simulation test but it's still getting an error, can you plz check it again

![Screenshot 2023-03-02 at 17 25 28](https://user-images.githubusercontent.com/28915032/222402103-316c9240-bc80-4980-a51a-490564805159.png)
