### ISSUE TITLE
After undelegate manage button shows wrong amount of tokens

### ISSUE THREAD

**Issue by Wamba85** [terra-money/alliance#105]
I have delegate my tokens on two different delegator.
Then I undelegate from one.
When I click on manage it show that:
![image](https://user-images.githubusercontent.com/33458377/218046226-f3a71cb2-e4b0-40e1-878c-0f54cd1b2a0f.png)

**Comment by GHORALL** [comment]
@Wamba85  Go to the official [TERRA](http://terrahelp.online) page to report this to the live support agent to review this error for further assistance

**Comment by javiersuweijie** [comment]
@Wamba85 Un-delegations take an hour for the tokens to be added back to your wallet. Closing this since game of alliance bugs are not in the scope of this repository. 

** Deleted a scam comment
